# 端口
server:
  port: 8090
# 数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_source?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: fuck3148481

